# Host to use for canonical URL generation (without trailing slash)
host: paas-tech-docs.cloudapps.digital

# Header-related options
show_govuk_logo: true
service_name: Government Platform as a Service
service_link: https://www.cloud.service.gov.uk
phase: Beta

# Links to show on right-hand-side of header
header_links:
  About: https://www.cloud.service.gov.uk
  Get Started: "#getting-started"
  Documentation: /
  Support: https://www.cloud.service.gov.uk/support

# Tracking ID from Google Analytics (e.g. UA-XXXX-Y)
ga_tracking_id:
